### ISSUE TITLE
show off the offending template when encountering a parsing error

### ISSUE THREAD

**Issue by looztra** [nodevops/confd-maven-plugin#14]
```
Caused by: com.github.nodevops.confd.maven.plugin.processors.ProcessorExecutionException: unable to process toml file  C:\root\relation-client-ihm-bp\relation-client-ihm-bp\target\confd\conf.d\
application.properties.toml
        at com.github.nodevops.confd.maven.plugin.processors.impl.JavaProcessorImpl.process(JavaProcessorImpl.java:40)
        at com.github.nodevops.confd.maven.plugin.mojo.ProcessMojo.execute(ProcessMojo.java:96)
        ... 22 more
Caused by: java.io.IOException: unterminated quoted string
        at com.github.nodevops.confd.maven.plugin.templating.LexicalAnalyzer.nextStringToken(LexicalAnalyzer.java:116)
        at com.github.nodevops.confd.maven.plugin.templating.LexicalAnalyzer.nextTokenInTemplateExpression(LexicalAnalyzer.java:61)
        at com.github.nodevops.confd.maven.plugin.templating.LexicalAnalyzer.nextToken(LexicalAnalyzer.java:21)
        at com.github.nodevops.confd.maven.plugin.templating.Parser.expectString(Parser.java:84)
        at com.github.nodevops.confd.maven.plugin.templating.Parser.evaluateTemplateExpression(Parser.java:59)
        at com.github.nodevops.confd.maven.plugin.templating.Parser.evaluateSource(Parser.java:47)
        at com.github.nodevops.confd.maven.plugin.templating.Parser.parse(Parser.java:30)
        at com.github.nodevops.confd.maven.plugin.processors.impl.JavaProcessorImpl.processToml(JavaProcessorImpl.java:84)
        at com.github.nodevops.confd.maven.plugin.processors.impl.JavaProcessorImpl.process(JavaProcessorImpl.java:38)
```

**Comment by looztra** [comment]
actually, this is already the case except for this particular template error "unterminated quoted string".

fixed by commit e7a9f1546a2cf843d6c99c88741d01e11534cea7
